name: cargo

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build (stable)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --manifest-path apps/server/Cargo.toml --verbose
  test:
    name: test (stable)
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo test --manifest-path apps/server/Cargo.toml --verbose
