name: cargo

on:
  # Only run tests if files changed in apps/server
  push:
    paths:
      - "apps/server/**"
  pull_request:
    paths:
      - "apps/server/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Build Project
        run: cargo build --manifest-path apps/server/Cargo.toml --verbose

      - name: Run Tests
        run: cargo test --manifest-path apps/server/Cargo.toml --verbose -- --nocapture
