name: Cargo

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build (stable)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Build Project
        run: cargo build --manifest-path apps/server/Cargo.toml --verbose

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: target

  test:
    name: Test (stable)
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: target

      - name: Run Tests
        run: cargo test --manifest-path apps/server/Cargo.toml --verbose -- --nocapture
